name: exhaustmap_with_trailing
description: An exhausmap implementation with trailing
version: 1.2.0
homepage: https://github.com/bjartebore/exhaustmap_with_trailing

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  rxdart: '>=0.27.0 <1.0.0'

dev_dependencies:
  test: ^1.25.15
  flutter_lints: ^5.0.0
